### PR TITLE
fix: Change the entrypoint CMD style

### PR DESCRIPTION
**Pull request by foadlind**
The previous CMD style breaks in Kubernetes deployments.

### CODE REVIEW

**Review by fghaas — CHANGES_REQUESTED** [review]
Change is fine; commit message is misleading: this breaks before we even get to Kubernetes. If anything, it would have to do with using Podman/Buildah rather than native Docker.

**Comment by fghaas** [comment]
@foadlind Could you please update the commit message so we can merge this?

**Comment by foadlind** [comment]
@fghaas I changed the commit message. Is it better?

**Review by fghaas — APPROVED** [review]
Looks good now, thanks!

**Pull request merged**
