### PR TITLE
feat: rename to "tutorwebhookreceiver", eliminate hyphens, use app.kubernetes.io/name labels and label selectors

### PR DESCRIPTION
**Pull request by fghaas**
* RFCs 1035/1123 require that DNS names do not contain underscores, although they can contain hyphens instead. docker-compose does not enforce this rule, but Kubernetes does. Fix the service and app names for Kubernetes, and for symmetry fix  them for docker-compose as well.

* Tutor relies on the `app.kubernetes.io/name` label (and label selectors) to be able to do things like `tutor k8s start <servicename>`. In the absence of those labels, this functionality breaks. Add those where needed.

### CODE REVIEW

**Comment by fghaas** [comment]
Copying comment from https://github.com/hastexo/tutor-contrib-webhook-receiver/pull/11#pullrequestreview-877169085:

> The reason I chose to rename to webhook_receiver in https://github.com/hastexo/tutor-contrib-webhook-receiver/pull/6 was to avoid problems with hyphens in Jinja2 template variables. With this PR, and https://github.com/hastexo/tutor-contrib-webhook-receiver/pull/10, sometimes we use underscore and sometimes hyphen in the name. I would rather we standardize on one or use some other name like webhookreceiver. What do you think?

Sure, that's another option and that's what other plugins use as well. If you can prepare a patch for that, then please put it in a fixup commit against my `fix-labels` branch, I pull that, then I do an squash rebase on my branch and we merge this PR. Sounds reasonable?

**Comment by foadlind** [comment]
@fghaas here is the commit: https://github.com/foadlind/tutor-contrib-webhook-receiver/commit/f8f129a691d083aee1ef4dd8861a9067166124d0. It is based on your `fix-labels` branch.

**Comment by foadlind** [comment]
I changed the name of the plugin folder to `tutorwebhookreceiver`. The new commit hash is https://github.com/foadlind/tutor-contrib-webhook-receiver/commit/955b6dbc219a7303ef7c7d6ec2121e9dcd5cdcdc.

**Comment by fghaas** [comment]
All right, cool. Thanks. :) So I suppose we now squash these three patches into one commit. Any objections?

**Comment by foadlind** [comment]
No objections :slightly_smiling_face:

**Comment by fghaas** [comment]
Okay. Can you give this one more test please?

**Comment by foadlind** [comment]
Testing now

**Comment by foadlind** [comment]
Everything works correctly locally (`tutor local quickstart`)

**Review by foadlind — APPROVED** [review]

**Comment by fghaas** [comment]
Right. `tutor k8s quickstart` works as well, but then the `webhookreceiver` container goes into a crash loop. But we'll look at that separately, as I don't believe it has anything to do with this change. I'll go ahead and merge this one now.

**Pull request merged**
